### ISSUE TITLE
memory error

### ISSUE THREAD

**Issue by wslj1993** [wwu-mmll/photonai#84]
when i import photonai,appear memory error?
![Uploading 微信截图_20240409092917.png…]()

**Comment by wslj1993** [comment]
![Uploading 微信截图_20240409092917.png…]()

**Comment by wslj1993** [comment]
that is
>>> import photonai 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\annaconda\envs\multivariate_biomarker\lib\site-packages\photonai\__init__.py", line 17, in <module>
  File "D:\annaconda\envs\multivariate_biomarker\lib\site-packages\photonai\processing\results_handler.py", line 8, in <module>
    import matplotlib
  File "D:\annaconda\envs\multivariate_biomarker\lib\site-packages\matplotlib\__init__.py", line 129, in <module>
    from . import _api, _version, cbook, _docstring, rcsetup
  File "D:\annaconda\envs\multivariate_biomarker\lib\site-packages\matplotlib\rcsetup.py", line 27, in <module>
    from matplotlib.colors import Colormap, is_color_like
  File "D:\annaconda\envs\multivariate_biomarker\lib\site-packages\matplotlib\colors.py", line 51, in <module>
    from PIL import Image
  File "D:\annaconda\envs\multivariate_biomarker\lib\site-packages\PIL\Image.py", line 84, in <module>
    from . import _imaging as core
ImportError: DLL load failed while importing _imaging: 内存资源不足，无法处理此命令。
